baseURL = "https://dataviz.vg/"
languageCode = "en-us"
title = "DATAVIZ.VG"
theme = "minimal"
googleAnalytics = "G-VC1T236FH5"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
    author = "Colin Fay"
    description = "📈 Dataviz for the Veg Community 🌱"
    githubUsername = "dataviz-vg"
    accent = "green"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]
    favicon = "/favicon.png"

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 2

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 3

[[menu.main]]
    url = "/resources/"
    name = "Resources"
    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "https://dataviz.vg/about/#contact"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/dataviz-vg"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/datavizvg/"
    name = "twitter"
    weight = 3
