---
title: Emissions by sector
author: colin
date: '2020-10-07'
slug: emissions-by-sector
categories: []
tags: []
draft: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE, 
  echo = FALSE, 
  warning = FALSE, 
  message = FALSE
)
```

# Sector by sector: where do global greenhouse gas emissions come from?


> Reference: Mekonnen, M.M. & Hoekstra, A.Y. (2011) The green, blue and grey water footprint of crops and derived crop products, Hydrology and Earth System Sciences, 15(5): 1577-1600.

https://ourworldindata.org/emissions-by-sector

https://github.com/owid/co2-data

```{r}
# df <- read_csv("https://raw.githubusercontent.com/owid/co2-data/master/owid-co2-data.csv")
```

# Methane (CH4) emissions by sector


```{r}
library(tidyverse)
df <- read_csv("data/methane-emissions-by-sector (1).csv")
df %>%
  pivot_longer(names_to = "sector", values_to = "amount", cols = 4:9) %>%
  group_by(Year, sector) %>%
  summarise(
    consumption = sum(amount, na.rm = TRUE)
  ) %>%
  ggplot(aes(Year, consumption, color = sector, group = sector)) + 
  geom_line(size = 2) + 
  scale_colour_viridis_d() + 
  theme_minimal() 

```

# Nitrous oxide (N2O) emissions by sector

```{r}
library(tidyverse)
df <- read_csv("data/nitrous-oxide-emissions-by-sector.csv")
df %>%
  pivot_longer(names_to = "sector", values_to = "amount", cols = 4:9) %>%
  group_by(Year, sector) %>%
  summarise(
    consumption = sum(amount, na.rm = TRUE)
  ) %>%
  ggplot(aes(Year, consumption, color = sector, group = sector)) + 
  geom_line(size = 2) + 
  scale_colour_viridis_d() + 
  theme_minimal()
```

# Per capita N2O: where do our emissions come from?

```{r}
library(tidyverse)
df <- read_csv("data/per-capita-nitrous-oxide-sector.csv")
df %>%
  pivot_longer(names_to = "sector", values_to = "amount", cols = 4:7) %>%
  group_by(Year, sector) %>%
  summarise(
    consumption = sum(amount, na.rm = TRUE)
  ) %>%
  ggplot(aes(Year, consumption, color = sector, group = sector)) + 
  geom_line(size = 2) + 
  scale_colour_viridis_d() + 
  theme_minimal()
```