---
title: Water consumption
author: colin
date: '2020-10-06'
slug: water-consumption
categories: []
tags: []
draft: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE, 
  echo = FALSE, 
  warning = FALSE, 
  message = FALSE
)
```

# Water footprints of farm animals and animal products (1996-2005)

> Reference: Mekonnen, M.M. & Hoekstra, A.Y. (2011) The green, blue and grey water footprint of crops and derived crop products, Hydrology and Earth System Sciences, 15(5): 1577-1600.

```{r}
library(tidyverse)
fls <- tempfile(fileext = ".zip")
download.file("https://www.waterfootprint.org/media/downloads/Report48-Appendix-V.zip", fls)
untar(fls, exdir = file.path(dirname(fls), "unzipped"))
list.files(file.path(dirname(fls), "unzipped"))
df <- readxl::read_excel(
  list.files(file.path(dirname(fls), "unzipped"), full.names = TRUE),
  2)
source_table <- readxl::read_excel(
  list.files(file.path(dirname(fls), "unzipped"), full.names = TRUE),
  2, skip = 2)
adjusted_table <- source_table %>%
  slice(-1) %>% 
  fill(`Product description (SITC)`) %>%
  select(`Product description (SITC)`, `World Average`) %>% 
  group_by(`Product description (SITC)`) %>%
  summarise(
    `World Average` = sum(as.numeric(`World Average`))
  ) %>%
  mutate(
    `Product description (SITC)` = reorder(`Product description (SITC)`, `World Average`)
  )
```

