---
title: Most freshwater withdrawals Products
author: colin
date: '2020-10-06'
slug: most-freshwater-withdrawals
categories: []
tags: []
draft: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE, 
  echo = FALSE, 
  warning = FALSE, 
  message = FALSE
)

```

> Reducing food’s environmental impacts through producers and consumers

https://science.sciencemag.org/content/360/6392/987/

```{r}
source("field_highwire_adjunct_files.R")
freshwater_withdrawals %>% 
  top_n(25) %>%
  gg_do_mean() +
  labs(
    title = "25 most freshwater withdrawals (By mean)", 
    subtitle = "From: 'Reducing food’s environmental impacts through producers and consumers'\nhttps://science.sciencemag.org/content/360/6392/987/",
    x = "Product", 
    y = "Mean freshwater withdrawals", 
    caption = "Via @VegViz"
  )
```

```{r}
freshwater_withdrawals %>% 
  top_n(25) %>%
  gg_do_median() +
  labs(
    title = "25 most freshwater withdrawals (By median)", 
    subtitle = "From: 'Reducing food’s environmental impacts through producers and consumers'\nhttps://science.sciencemag.org/content/360/6392/987/",
    x = "Product", 
    y = "Median eutrophying emissions", 
    caption = "Via @VegViz"
  )
```
