# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

name: R-CMD-check

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck", "blogdown"))
          remotes::install_github('datavizvg/vegviz')
        shell: Rscript {0}
      - name: Install Hugo
        run: Rscript -e 'blogdown::install_hugo()'
      - name: Build site
        run: Rscript -e 'blogdown::build_site()'
  checkout-and-deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Deploy to GitHub Pages
      uses: Cecilapp/GitHub-Pages-deploy@master
      env:
        EMAIL: contact@colinfay.me
        GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BUILD_DIR: public
        