# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

name: R-CMD-check

jobs:
  checkout-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Install sysreq
        run: sudo apt update && sudo apt install -y libcurl4-openssl-dev
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "blogdown"))
          remotes::install_github('datavizvg/vegviz')
        shell: Rscript {0}
      - name: Install Hugo
        run: Rscript -e 'blogdown::install_hugo()'
      - name: Build site
        run: Rscript -e 'blogdown::build_site()'
      - name: Commit files
        run: |
          git config --local user.email "contact@colinfay.me"
          git config --local user.name "GitHub Action"
          git commit -m "Built" -a
      - name: Push to built branch
        uses: Automattic/action-commit-to-branch@master
        with:
          branch: 'gh-pages'
          commit_message: 'Build master'
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }} # Required
